name: example-attest-basic
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: bridgedai-devsecops/subject-action@v1.0.0
        id: subj
        with:
          subject: examples/predicate.json
          subject-type: file
          mode: mock
      - uses: bridgedai-devsecops/attest-action@v1.0.0
        with:
          subject-name: predicate.json
          subject-digest: ${{ steps.subj.outputs.subject-digest }}
          predicate-type: https://slsa.dev/provenance/v1
          predicate-file: examples/predicate.json
          attestation-file: .bridgedai/attestation.json
          mode: create-only
          signer: cosign
          upload-to-rekor: 'false'
          verify-rekor: 'false'

